/* 
**  mod_sleep.c -- Apache sample sleep module
**  [Autogenerated via ``apxs -n sleep -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_sleep.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /sleep in as follows:
**
**    #   httpd.conf
**    LoadModule sleep_module modules/mod_sleep.so
**    <Location /sleep>
**        SetHandler sleep
**        SetSleep   1000
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /sleep and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/sleep 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**    X-Sleep: 1000ms
**  
**    The sample page from mod_sleep.c
*/ 

#include <stdio.h>
#include <unistd.h>
#include <sys/time.h>
#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "http_log.h"

module AP_MODULE_DECLARE_DATA sleep_module;

/* The sample content handler */
static int sleep_handler(request_rec *r)
{
	if(strcmp(r->handler,"sleep")){
		return DECLINED;
	}

        int *slp = (int*)ap_get_module_config(r->per_dir_config,&sleep_module);

	if(*slp < 1)
		return DECLINED;

	usleep(*slp);

	char str[32]={'\0'};

	sprintf(str,"%dms",*slp);

	apr_table_set(r->headers_out,"X-Sleep",str);

	return DECLINED;
}

static void sleep_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(sleep_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

static void *create_dir_config(apr_pool_t *p, char *dir){
	int *slp = (int*)apr_palloc(p,sizeof(int));
	*slp = 0;
	return (void*)slp;
}

static const char *set_sleep(cmd_parms *cmd, void *_slp, const char *s_slp){
	int *slp = (int*)_slp;

	*slp = atoi(s_slp) * 1000;

	if(*slp < 1)
		return "specify natural number for SetSleep";

	return NULL;
}

static const command_rec cmds[] = {
	AP_INIT_TAKE1("SetSleep",set_sleep,NULL,OR_LIMIT,"specify sleep time"),
	{NULL}
};

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA sleep_module = {
    STANDARD20_MODULE_STUFF, 
    create_dir_config,     /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    cmds,                  /* table of config file commands       */
    sleep_register_hooks  /* register hooks                      */
};

